### ISSUE TITLE
Does nothing in 4.1.1

### ISSUE THREAD

**Issue by Chronos-89** [anatolbogun/godot-smoother-node#4]
Position no longer changes when smoother is active, but works again if it's deactivated. 
Was working fine in 4.0 and even 4.1.1 but the latest update killed it yet again.

**Comment by anatolbogun** [comment]
@Rukiri, thanks for raising this issue. However, I cannot reproduce it. I just tested it in the latest stable version `v4.1.1.stable.official [bd6af8e0e]`, and in the latest dev snapshot `v4.2.dev5.official [e3e2528ba]`, but in both the Smoother node worked as expected. I tried it in this [Test Scene](https://github.com/anatolbogun/godot-smoother-node-test-scene) and when I turned the node processing on and off the difference was apparent.

Is there any specific setup in your case that may cause the issue?

> the latest update killed it yet again
For clarification, do you mean the latest Godot or the latest Smoother Node update?

I did get a few debug warnings in newer Godot versions, and these [should be fixed in the latest commit](https://github.com/anatolbogun/godot-smoother-node/commit/dca0839d8abf789b617b1d4e9aa3de4f28c93f4a), but these warnings didn't break anything in my tests.

I also submitted the latest update to the official Godot asset library and the listing will be updated after that's reviewed—in the meantime, [you can use the latest version here](https://github.com/anatolbogun/godot-smoother-node/blob/main/smoother.gd).

**Comment by elvisish** [comment]
Can confirm it works perfectly on 4.1.1 (I still can't believe how well this works just by throwing the node in the scene, its incredible).
